export const DOCUMENT = Object.freeze({
  USER_PICTURE : "USER PICTURE",
  VECHILE_PICTURE : "VECHILE PICTURE",
  USER_DOCUMENT : "USER DOCUMENT",
  VEHICLE_DOCUMENT : "VEHICLE DOCUMENT",
  RESTAURANT_DOCUMENT : "RESTAURANT DOCUMENT"
});